export const GROUP_LOADING = 'GROUP_LOADING';
export const GROUP_SUCCESS = 'GROUP_SUCCESS';
export const GROUP_ERROR = 'GROUP_ERROR';
export const GET_GROUPS_USER_SUBSCRIBES = 'GET_GROUPS_USER_SUBSCRIBES';
export const GROUP_ADD = 'GROUP_ADD';
export const GROUP_UPDATE = 'GROUP_UPDATE';
export const GROUP_CHANGE_SUB = 'GROUP_CHANGE_SUB'

export const GROUP_COMMIT_SUBSCRIPTION = 'GROUP_COMMIT_SUBSCRIPTION';
export const GROUP_COMMIT_SUBSCRIPTION_LOADING = 'GROUP_COMMIT_SUBSCRIPTION_LOADING';
export const GROUP_COMMIT_SUBSCRIPTION_SUCCESS = 'GROUP_COMMIT_SUBSCRIPTION_SUCCESS';
export const GROUP_COMMIT_SUBSCRIPTION_FAILURE = 'GROUP_COMMIT_SUBSCRIPTION_FAILURE';

export const GROUP_DELETE = 'GROUP_DELETE'