// Authentication and Users
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_ERROR = 'USER_ERROR'


// Messages
export const INIT_MESSAGE = 'INIT_MESSAGE';
export const GET_MESSAGE = 'GET_MESSAGE';
export const GET_ERROR = 'GET_ERROR';

// Server data
export const BASE_DATA_LOADING = 'BASE_DATA_LOADING';
export const BASE_DATA_SUCCESS = 'BASE_DATA_SUCCESS';
export const STATS_INPUTS_LOADING = 'STATS_INPUTS_LOADING';
export const STATS_INPUTS_SUCCESS = 'STATS_INPUTS_SUCCESS';

// Paths
export const PATH_LOADING = 'PATH_LOADING';
export const PATH_SUCCESS = 'PATH_SUCCESS';
export const PATH_ERROR = 'PATH_ERROR';
export const PATH_ADD = 'PATH_ADD';
export const PATH_UPDATE = 'PATH_UPDATE';
export const PATH_DELETE = 'PATH_DELETE';



// Sections
export const SEC_LOADING = 'SEC_LOADING';
export const SEC_SUCCESS = 'SEC_SUCCESS';
export const SEC_ERROR = 'SEC_ERROR';
export const SEC_ADD = 'SEC_ADD';
export const SEC_UPDATE = 'SEC_UPDATE';
export const SEC_DELETE = 'SEC_DELETE';
export const ITEM_ADD = 'ITEM_ADD';
export const ITEM_UPDATE = 'ITEM_UPDATE';
export const ITEM_DELETE = 'ITEM_DELETE';

// Steps
export const STEP_LOADING = 'STEP_LOADING';
export const STEP_SUCCESS = 'STEP_SUCCESS';
export const STEP_ERROR = 'STEP_ERROR';
export const STEP_ADD = 'STEP_ADD';
export const STEP_UPDATE = 'STEP_UPDATE';
export const STEP_DELETE = 'STEP_DELETE';
export const STEP_ADD_LINK_LABEL = 'STEP_ADD_LINK_LABEL';
export const STEP_ADD_SUMMARY = 'STEP_ADD_SUMMARY';
export const STEP_EDIT_SUMMARY = 'STEP_EDIT_SUMMARY';
export const STEP_REMOVE_SUMMARY = 'STEP_REMOVE_SUMMARY';
export const STEP_ADD_SUMMARY_GROUP = 'STEP_ADD_SUMMARY_GROUP';
export const STEP_ADD_SUMMARY_CONTENT = 'STEP_ADD_SUMMARY_CONTENT';
export const STEP_EDIT_SUMMARY_CONTENT = 'STEP_EDIT_SUMMARY_CONTENT';
export const STEP_REMOVE_SUMMARY_CONTENT = 'STEP_REMOVE_SUMMARY_CONTENT';
export const STEP_ADD_UNI_CONTENT = 'STEP_ADD_UNI_CONTENT';
export const STEP_FILTER_UNIS = 'STEP_FILTER_UNIS';



// Libraries
export const LIBRARY_LOADING = 'LIBRARY_LOADING';
export const LIBRARY_SUCCESS = 'LIBRARY_SUCCESS';
export const LIBRARY_ERROR = 'LIBRARY_ERROR';
export const LIBRARY_ADD = 'LIBRARY_ADD';
export const LIBRARY_UPDATE = 'LIBRARY_UPDATE';
export const LIBRARY_DELETE = 'LIBRARY_DELETE';
// export const LIBRARY_LINK_ADD = 'LIBRARY_LINK_ADD';
// export const LIBRARY_LINK_UPDATE = 'LIBRARY_LINK_EDIT';
// export const LIBRARY_LINK_DELETE = 'LIBRARY_LINK_DELETE';

// Topics
export const LIB_ITEM_ADD = 'LIB_ITEM_ADD';
export const LIB_ITEM_EDIT = 'LIB_ITEM_EDIT';
export const LIB_ITEM_DELETE = 'LIB_ITEM_DELETE';
export const LIB_ITEM_TOGGLE_VOTE = 'LIB_ITEM_TOGGLE_VOTE';
// export const LIB_ITEM_ITEM_COMMENT_ADD = 'LIB_ITEM_ITEM_COMMENT_ADD';
// export const LIB_ITEM_ITEM_COMMENT_UPDATE = 'LIB_ITEM_ITEM_COMMENT_UPDATE';
// export const LIB_ITEM_ITEM_COMMENT_TOGGLE_LIKE = 'LIB_ITEM_ITEM_COMMENT_TOGGLE_LIKE';
// export const LIB_ITEM_ITEM_COMMENT_DELETE = 'LIB_ITEM_ITEM_COMMENT_DELETE';

// Data Groups
export const DATA_GROUP_LOADING = 'DATA_GROUP_LOADING';
export const DATA_GROUP_SUCCESS = 'DATA_GROUP_SUCCESS';
export const DATA_GROUP_ERROR = 'DATA_GROUP_ERROR';
export const DATA_GROUP_ADD = 'DATA_GROUP_ADD';
export const DATA_GROUP_UPDATE = 'DATA_GROUP_UPDATE';
export const DATA_GROUP_DELETE = 'DATA_GROUP_DELETE';
export const DATA_GROUP_ASSIGN_ROLE = 'DATA_GROUP_ASSIGN_ROLE';

// Data Fields
export const DATA_FIELD_LOADING = 'DATA_FIELD_LOADING';
export const DATA_FIELD_SUCCESS = 'DATA_FIELD_SUCCESS';
export const DATA_FIELD_ERROR = 'DATA_FIELD_ERROR';
export const ALLOWED_TYPES_GET = 'ALLOWED_TYPES_GET';
export const DATA_FIELD_ADD = 'DATA_FIELD_ADD';
export const DATA_FIELD_UPDATE = 'DATA_FIELD_UPDATE';
export const DATA_FIELD_DELETE = 'DATA_FIELD_DELETE';
export const DATA_FIELD_VALID_ADD = 'DATA_FIELD_VALID_ADD';
export const DATA_FIELD_VALID_UPDATE = 'DATA_FIELD_VALID_EDIT';
export const DATA_FIELD_VALID_DELETE = 'DATA_FIELD_VALID_DELETE';
export const DATA_FIELD_OPTION_ADD = 'DATA_FIELD_OPTION_ADD';
export const DATA_FIELD_OPTION_DELETE = 'DATA_FIELD_OPTION_DELETE';
export const DATA_FIELD_ASSIGN_ROLE = 'DATA_FIELD_ASSIGN_ROLE';


// Universities
export const UNI_LOADING = 'UNI_LOADING';
export const UNI_SUCCESS = 'UNI_SUCCESS';
export const UNI_ERROR = 'UNI_ERROR';
export const UNI_ADD = 'UNI_ADD';
export const UNI_UPDATE = 'UNI_UPDATE';
export const UNI_DELETE = 'UNI_DELETE';

// Calcualtions
export const CALC_LOADING = 'CALC_LOADING';
export const CALC_SUCCESS = 'CALC_SUCCESS';
export const CALC_ERROR = 'CALC_ERROR';
export const CALC_ADD = 'CALC_ADD';
export const CALC_UPDATE = 'CALC_UPDATE';
export const STORED_CALCS_GET = 'STORED_CALCS_GET';
export const CALC_ASSIGN_ROLE = 'CALC_ASSIGN_ROLE';
export const CALC_DELETE = 'CALC_DELETE';


// User data
export const USER_DATA_LOADING = 'USER_DATA_LOADING';
export const USER_DATA_LOAD_SOFT = 'USER_DATA_LOAD_SOFT';
export const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS';
export const USER_DATA_PATH_SUCCESS = 'USER_DATA_PATH_SUCCESS';
export const USER_DATA_ERROR = 'USER_DATA_ERROR';
export const VALID_ERROR = 'VALID_ERROR';
export const USER_DATA_ADD = 'USER_DATA_ADD';
export const CHANGE_TABLE = 'CHANGE_TABLE';
export const GET_TABLE_SETCIONS = 'GET_TABLE_SETCIONS';

export const SIMULATE_CALCS = 'SIMULATE_CALCS';
export const COPY_DATA_SIMULATION = 'COPY_DATA_SIMULATION';
export const INSERT_DATA_SIMULATION = 'INSERT_DATA_SIMULATION';
export const REMOVE_SIMULATED_VALUES = 'REMOVE_SIMULATED_VALUES';
export const ADD_SIMULATED_GROUP = 'ADD_SIMULATED_GROUP'; 
export const VALID_ERROR_SIMULATED = 'VALID_ERROR_SIMULATED';
export const REMOVE_SIMULATED_GROUP = 'REMOVE_SIMULATED_GROUP';
 
export const USER_DATA_UPDATE_PATHS = 'USER_DATA_UPDATE_PATHS';
export const USER_DATA_SWITCH_TABLE = 'USER_DATA_SWITCH_TABLE';
export const USER_DATA_INSERT = 'USER_DATA_INSERT';
export const USER_DATA_REMOVE = 'USER_DATA_REMOVE';
export const USER_DATA_TOGGLE_ENABLED = 'USER_DATA_TOGGLE_ENABLED';
export const EXEC_CALC = 'EXEC_CALC';
export const ADD_CUSTOM_GROUP = 'ADD_CUSTOM_GROUP';
export const USER_DATA_DELETE = 'USER_DATA_DELETE';
export const FILTER_DATA = 'FILTER_DATA';
export const REMOVE_FILTER_DATA = 'REMOVE_FILTER_DATA';
export const SORT_DATA = 'SORT_DATA';


// Data Tables
export const TABLE_LOADING = 'TABLE_LOADING';
export const TABLE_SUCCESS = 'TABLE_SUCCESS';
export const TABLE_ERROR = 'TABLE_ERROR';
export const TABLE_ADD = 'TABLE_ADD';
export const TABLE_UPDATE = 'TABLE_UPDATE';
export const TABLE_TOGGLE_ENABLED = 'TABLE_TOGGLE_ENABLED';
export const TABLE_DELETE = 'TABLE_DELETE';
export const THRESHOLD_ADD = 'THRESHOLD_ADD';
export const THRESHOLD_UPDATE = 'THRESHOLD_UPDATE';
export const THRESHOLD_DELETE = 'THRESHOLD_DELETE';

// Question Groups
export const QUEST_GROUP_LOADING = 'QUEST_GROUP_LOADING';
export const QUEST_GROUP_SUCCESS = 'QUEST_GROUP_SUCCESS';
export const QUEST_GROUP_ERROR = 'QUEST_GROUP_ERROR';
export const QUEST_GROUP_ADD = 'QUEST_GROUP_ADD';
export const QUEST_GROUP_UPDATE = 'QUEST_GROUP_UPDATE';
export const QUEST_GROUP_DELETE = 'QUEST_GROUP_DELETE';
export const QUEST_ADD = 'QUEST_ADD';
export const QUEST_UPDATE = 'QUEST_UPDATE';
export const QUEST_DELETE = 'QUEST_DELETE';


// Inquiries 
export const INQUIRY_LOADING = 'INQUIRY_LOADING';
export const INQUIRY_SUCCESS = 'INQUIRY_SUCCESS';
export const INQUIRY_ERROR = 'INQUIRY_ERROR';
export const GET_INQUIRY_TYPES = 'GET_INQUIRY_TYPES';
export const INQUIRY_ADD = 'INQUIRY_ADD';
export const INQUIRY_UPDATE = 'INQUIRY_UPDATE';
export const INQUIRY_ASSIGN_ADMIN = 'INQUIRY_ASSING_ADMIN';
export const INQUIRY_CHANGE_STATUS = 'INQUIRY_CHANGE_STATUS';
export const INQUIRY_UPDATE_STATUS_NOTE = 'INQUIRY_UPDATE_STATUS_NOTE';
export const INQUIRY_DELETE = 'INQUIRY_DELETE';

