// Authentication and Users
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_ERROR = 'USER_ERROR'


// Messages
export const INIT_MESSAGE = 'INIT_MESSAGE';
export const GET_MESSAGE = 'GET_MESSAGE';
export const GET_ERROR = 'GET_ERROR';

// Paths
export const PATH_LOADING = 'PATH_LOADING';
export const PATH_SUCCESS = 'PATH_SUCCESS';
export const PATH_ERROR = 'PATH_ERROR';
export const PATH_ADD = 'PATH_ADD';
export const PATH_UPDATE = 'PATH_UPDATE';
export const PATH_DELETE = 'PATH_DELETE';

// Anouncement Groups
export const GROUP_LOADING = 'GROUP_LOADING';
export const GROUP_SUCCESS = 'GROUP_SUCCESS';
export const GROUP_ERROR = 'GROUP_ERROR';
export const USER_SUBSCRIBES = 'USER_SUBSCRIBES';
export const GROUP_ADD = 'GROUP_ADD';
export const GROUP_UPDATE = 'GROUP_UPDATE';
export const GROUP_SUBSCRIBE = 'GROUP_SUBSCRIBE';
export const GROUP_UNSUBSCRIBE = 'GROUP_UNSUBSCRIBE';
export const GROUP_DELETE = 'GROUP_DELETE';

// Anouncements
export const ANC_LOADING = 'ANC_LOADING';
export const ANC_SUCCESS = 'ANC_SUCCESS';
export const ANC_ERROR = 'ANC_ERROR';
export const ANC_ADD = 'ANC_ADD';
export const ANC_UPDATE = 'ANC_UPDATE';
export const ANC_DELETE = 'ANC_DELETE';

// Sections
export const SEC_LOADING = 'SEC_LOADING';
export const SEC_SUCCESS = 'SEC_SUCCESS';
export const SEC_ERROR = 'SEC_ERROR';
export const SEC_ADD = 'SEC_ADD';
export const SEC_UPDATE = 'SEC_UPDATE';
export const SEC_DELETE = 'SEC_DELETE';
export const ITEM_ADD = 'ITEM_ADD';
export const ITEM_UPDATE = 'ITEM_UPDATE';
export const ITEM_DELETE = 'ITEM_DELETE';

// Steps
export const STEP_LOADING = 'STEP_LOADING';
export const STEP_SUCCESS = 'STEP_SUCCESS';
export const STEP_ERROR = 'STEP_ERROR';
export const STEP_ADD = 'STEP_ADD';
export const STEP_UPDATE = 'STEP_UPDATE';
export const STEP_DELETE = 'STEP_DELETE';

// Pages
export const PAGE_LOADING = 'PAGE_LOADING';
export const PAGE_SUCCESS = 'PAGE_SUCCESS';
export const PAGE_ERROR = 'PAGE_ERROR';
export const PAGE_ADD = 'PAGE_ADD';
export const PAGE_UPDATE = 'PAGE_UPDATE';
export const PAGE_DELETE = 'PAGE_DELETE';
export const PAGE_LINK_ADD = 'PAGE_LINK_ADD';
export const PAGE_LINK_UPDATE = 'PAGE_LINK_EDIT';
export const PAGE_LINK_DELETE = 'PAGE_LINK_DELETE';

// Topics
export const TOPIC_LOADING = 'TOPIC_LOADING';
export const TOPIC_SUCCESS = 'TOPIC_SUCCESS';
export const TOPIC_ERROR = 'TOPIC_ERROR';
export const TOPIC_ADD = 'TOPIC_ADD';
export const TOPIC_UPDATE = 'TOPIC_UPDATE';
export const TOPIC_DELETE = 'TOPIC_DELETE';
export const TOPIC_ITEM_ADD = 'TOPIC_ITEM_ADD';
export const TOPIC_ITEM_UPDATE = 'TOPIC_ITEM_EDIT';
export const TOPIC_ITEM_TOGGLE_UPVOTE = 'TOPIC_ITEM_TOGGLE_UPVOTE';
export const TOPIC_ITEM_TOGGLE_DOWNVOTE = 'TOPIC_ITEM_TOGGLE_DOWNVOTE';
export const TOPIC_ITEM_COMMENT_ADD = 'TOPIC_ITEM_COMMENT_ADD';
export const TOPIC_ITEM_COMMENT_UPDATE = 'TOPIC_ITEM_COMMENT_UPDATE';
export const TOPIC_ITEM_COMMENT_TOGGLE_LIKE = 'TOPIC_ITEM_COMMENT_TOGGLE_LIKE';
export const TOPIC_ITEM_COMMENT_DELETE = 'TOPIC_ITEM_COMMENT_DELETE';
export const TOPIC_ITEM_DELETE = 'TOPIC_ITEM_DELETE';

// Data Groups
export const DATA_GROUP_LOADING = 'DATA_GROUP_LOADING';
export const DATA_GROUP_SUCCESS = 'DATA_GROUP_SUCCESS';
export const DATA_GROUP_ERROR = 'DATA_GROUP_ERROR';
export const DATA_GROUP_ADD = 'DATA_GROUP_ADD';
export const DATA_GROUP_UPDATE = 'DATA_GROUP_UPDATE';
export const DATA_GROUP_DELETE = 'DATA_GROUP_DELETE';
export const DATA_GROUP_ASSIGN_ROLE = 'DATA_GROUP_ASSIGN_ROLE';

// Data Fields
export const DATA_FIELD_LOADING = 'DATA_FIELD_LOADING';
export const DATA_FIELD_SUCCESS = 'DATA_FIELD_SUCCESS';
export const DATA_FIELD_ERROR = 'DATA_FIELD_ERROR';
export const ALLOWED_TYPES_GET = 'ALLOWED_TYPES_GET';
export const DATA_FIELD_ADD = 'DATA_FIELD_ADD';
export const DATA_FIELD_UPDATE = 'DATA_FIELD_UPDATE';
export const DATA_FIELD_DELETE = 'DATA_FIELD_DELETE';
export const DATA_FIELD_VALID_ADD = 'DATA_FIELD_VALID_ADD';
export const DATA_FIELD_VALID_UPDATE = 'DATA_FIELD_VALID_EDIT';
export const DATA_FIELD_VALID_DELETE = 'DATA_FIELD_VALID_DELETE';
export const DATA_FIELD_OPTION_ADD = 'DATA_FIELD_OPTION_ADD';
export const DATA_FIELD_OPTION_DELETE = 'DATA_FIELD_OPTION_DELETE';
export const DATA_FIELD_ASSIGN_ROLE = 'DATA_FIELD_ASSIGN_ROLE';


// Universities
export const UNI_LOADING = 'UNI_LOADING';
export const UNI_SUCCESS = 'UNI_SUCCESS';
export const UNI_ERROR = 'UNI_ERROR';
export const UNI_ADD = 'UNI_ADD';
export const UNI_UPDATE = 'UNI_UPDATE';
export const UNI_DELETE = 'UNI_DELETE';

// Calcualtions
export const CALC_LOADING = 'CALC_LOADING';
export const CALC_SUCCESS = 'CALC_SUCCESS';
export const CALC_ERROR = 'CALC_ERROR';
export const CALC_ADD = 'CALC_ADD';
export const CALC_UPDATE = 'CALC_UPDATE';
export const STORED_CALCS_GET = 'STORED_CALCS_GET';
export const CALC_ASSIGN_ROLE = 'CALC_ASSIGN_ROLE';
export const CALC_DELETE = 'CALC_DELETE';


// User data
export const USER_DATA_LOADING = 'USER_DATA_LOADING';
export const USER_DATA_LOAD_SOFT = 'USER_DATA_LOAD_SOFT';
export const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS';
export const COPY_DATA_SIMULATION = 'COPY_DATA_SIMULATION' 
export const USER_DATA_PATH_SUCCESS = 'USER_DATA_PATH_SUCCESS';
export const USER_DATA_ERROR = 'USER_DATA_ERROR';
export const USER_DATA_ADD = 'USER_DATA_ADD';
export const SIMULATE_CALCS = 'SIMULATE_CALCS';
export const USER_DATA_UPDATE_PATHS = 'USER_DATA_UPDATE_PATHS';
export const USER_DATA_SWITCH_TABLE = 'USER_DATA_SWITCH_TABLE'
export const USER_DATA_INSERT = 'USER_DATA_INSERT';
export const USER_DATA_TOGGLE_ENABLED = 'USER_DATA_TOGGLE_ENABLED';
export const EXEC_CALC = 'EXEC_CALC';
export const USER_DATA_DELETE = 'USER_DATA_DELETE';
export const FILTER_DATA = 'FILTER_DATA';
export const REMOVE_FILTER_DATA = 'REMOVE_FILTER_DATA';
export const SORT_DATA = 'SORT_DATA';


// Data Tables
export const TABLE_LOADING = 'TABLE_LOADING';
export const TABLE_SUCCESS = 'TABLE_SUCCESS';
export const TABLE_ERROR = 'TABLE_ERROR';
export const TABLE_ADD = 'TABLE_ADD';
export const TABLE_UPDATE = 'TABLE_UPDATE';
export const TABLE_TOGGLE_ENABLED = 'TABLE_TOGGLE_ENABLED';
export const TABLE_DELETE = 'TABLE_DELETE';


// Question Groups
export const QUEST_GROUP_LOADING = 'QUEST_GROUP_LOADING';
export const QUEST_GROUP_SUCCESS = 'QUEST_GROUP_SUCCESS';
export const QUEST_GROUP_ERROR = 'QUEST_GROUP_ERROR';
export const QUEST_GROUP_ADD = 'QUEST_GROUP_ADD';
export const QUEST_GROUP_UPDATE = 'QUEST_GROUP_UPDATE';
export const QUEST_GROUP_DELETE = 'QUEST_GROUP_DELETE';
export const QUEST_ADD = 'QUEST_ADD';
export const QUEST_UPDATE = 'QUEST_UPDATE';
export const QUEST_DELETE = 'QUEST_DELETE';


// Inquiries 
export const INQUIRY_LOADING = 'INQUIRY_LOADING';
export const INQUIRY_SUCCESS = 'INQUIRY_SUCCESS';
export const INQUIRY_ERROR = 'INQUIRY_ERROR';
export const GET_INQUIRY_TYPES = 'GET_INQUIRY_TYPES';
export const INQUIRY_ADD = 'INQUIRY_ADD';
export const INQUIRY_UPDATE = 'INQUIRY_UPDATE';
export const INQUIRY_ASSIGN_ADMIN = 'INQUIRY_ASSING_ADMIN';
export const INQUIRY_CHANGE_STATUS = 'INQUIRY_CHANGE_STATUS';
export const INQUIRY_UPDATE_STATUS_NOTE = 'INQUIRY_UPDATE_STATUS_NOTE';
export const INQUIRY_DELETE = 'INQUIRY_DELETE';

