// Comments
export const COMMENT_LOADING = 'COMMENT_LOADING';
export const COMMENT_GET_BY_ITEM = 'COMMENT_GET_BY_ITEM';
export const COMMENT_ERROR = 'COMMENT_ERROR';
export const COMMENT_ADD = 'COMMENT_ADD';
export const COMMENT_TOGGLE_LIKE = 'COMMENT_TOGGLE_LIKE';
export const COMMENT_UPDATE = 'COMMENT_UPDATE';
export const COMMENT_DELETE = 'COMMENT_DELETE';